# getInfo() fails: bpApiBaseUrl: https://api.eosnewyork.io
# 1.7-2.5 sec: bpApiBaseUrl: https://api.bp.fish
# 1.8-2.3, with one at 6.7 sec: bpApiBaseUrl: https://api.eosdetroit.io:443
# 1.3-1.5 sec: bpApiBaseUrl: http://api1.eosdublin.io:80
bpApiBaseUrl: http://api1.eosdublin.io:80
# 2-6 sec: bpApiBaseUrl: https://api.cypherglass.com:443
# *very* variable response times: bpApiBaseUrl: http://bp.cryptolions.io:8888
# 2-3 sec bpApiBaseUrl: https://eu1.eosdac.io:443
middlewarePortNumber: 3001
chainId: aca376f206b8fc25a6ed44dbdc66547c36c6c33e3a119ffbeaef943642f0e906

